# Generated by Django 4.2.6 on 2023-11-02 21:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("flight", "0002_airport_alter_flight_destination_alter_flight_origin"),
    ]

    operations = [
        migrations.AddField(
            model_name="airport",
            name="code",
            field=models.CharField(default=django.utils.timezone.now, max_length=3),
            preserve_default=False,
        ),
    ]
