# Generated by Django 4.2.6 on 2023-11-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight", "0003_airport_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="Passenger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first", models.CharField(max_length=64)),
                ("last", models.CharField(max_length=64)),
                (
                    "flights",
                    models.ManyToManyField(
                        blank=True, related_name="passenger", to="flight.flight"
                    ),
                ),
            ],
        ),
    ]
